#!/usr/bin/env bash

dockerTag="${DOCKER_TAG%%_*}"

baseImage="${dockerTag%%-*}"
releaseTag="${dockerTag#*-}"

case "$baseImage" in
  'alpine')
    baseBuilderImage="golang:alpine"
    baseImage="alpine"
    dockerfile="AlpineDockerfile"
  ;;
  'stretch')
    baseBuilderImage="golang:stretch"
    baseImage="debian:stretch-slim"
    dockerfile="DebianDockerfile"
  ;;
  *)
    echo "Invalid variable DOCKER_TAG='$DOCKER_TAG'. Only 'alpine-.*' and 'stretch-.*' are supported." 1>&2
    exit 1
  ;;
esac

IMAGE_NAME="$DOCKER_REPO:$dockerTag"

set -x

docker build\
 --build-arg RELEASE_VERSION="$baseBuilderImage"\
 --build-arg BASE_IMAGE="$baseImage"\
 --build-arg RELEASE_TAG="$releaseTag"\
  -t "$IMAGE_NAME"\
  -f "$dockerfile" .
