#!/usr/bin/env bash

if [[ "$DOCKER_TAG" == *latest ]]; then
  baseImage="${DOCKER_TAG%%-*}"
  latestTag="$DOCKER_REPO:$baseImage-latest"
  docker tag "$IMAGE_NAME" "$latestTag"
  docker push "$latestTag"
fi
