#!/usr/bin/env bash

readonly dockerTag="${DOCKER_TAG%%_*}"
IMAGE_NAME="$DOCKER_REPO:$dockerTag"

docker push "$IMAGE_NAME"

if [[ "$DOCKER_TAG" == *latest ]]; then
  readonly baseImage="${DOCKER_TAG%%-*}"
  readonly latestTag="$DOCKER_REPO:$baseImage-latest"
  docker tag "$IMAGE_NAME" "$latestTag"
  docker push "$latestTag"
fi
